export const B = {
  navy:    '#0F172A',
  navyMid: '#1E293B',
  navyLt:  '#334155',
  emerald: '#10B981',
  teal:    '#14B8A6',
  blue:    '#3B82F6',
  text:    '#F8FAFC',
  muted:   '#94A3B8',
  dim:     '#64748B',
  error:   '#EF4444',
  warn:    '#F59E0B',
  grad:    'linear-gradient(135deg, #10B981, #14B8A6)',
} as const;

export const TOOLTIPS: Record<string, { title: string; body: string }> = {
  olfiScore: {
    title: 'OLFI Score',
    body: 'OLFI Score is our proprietary credit-health metric combining your CBUAE bureau data, open-banking cash flow, payment discipline, and employment stability. Unlike a static bureau score, it updates in real-time and factors in your full financial behaviour.',
  },
  cbuaeScore: {
    title: 'CBUAE Credit Score',
    body: 'The CBUAE (Central Bank of UAE) credit score is the official bureau score issued by Al Etihad Credit Bureau (AECB). It ranges from 300 to 900 and reflects your repayment history across all UAE lenders. OLFI provides this score to you for free.',
  },
  murabaha: {
    title: 'Murābaḥa (مرابحة)',
    body: 'A Sharia-compliant sale contract where the bank buys an asset and sells it to you at a disclosed profit margin. No interest (riba) is charged. You pay in instalments at a fixed profit rate — fully halal.',
  },
  tawarruq: {
    title: 'Tawarruq (التورق)',
    body: 'A Sharia-compliant liquidity instrument. The bank purchases a commodity and sells it to you on a deferred basis. You then sell it to raise cash. Used for personal financing without riba.',
  },
  ijara: {
    title: 'Ijāra (الإجارة)',
    body: 'An Islamic leasing arrangement — the bank buys an asset and leases it to you for a fixed period. Similar to a hire-purchase but structured to be free of interest. Common for auto and property financing.',
  },
  dbr: {
    title: 'Debt Burden Ratio (DBR)',
    body: "DBR is the percentage of your monthly income that goes toward debt repayments. The CBUAE caps DBR at 50% for salaried UAE residents. A lower DBR improves your refinance eligibility and the profit rates lenders offer you.",
  },
  apr: {
    title: 'APR / Profit Rate',
    body: "For Sharia-compliant products, we show a 'profit rate' rather than an interest rate. It works similarly — it's the annual cost of the financing expressed as a percentage of the outstanding amount. Lower is better.",
  },
  emi: {
    title: 'EMI (Equal Monthly Instalment)',
    body: 'Your fixed monthly payment toward a loan or financing facility. It covers both the principal amount and the profit/interest. Refinancing typically aims to reduce your EMI by securing a lower profit rate or extending the tenure.',
  },
};

export const TRANSLATIONS = {
  en: {
    getStarted: 'Get Started', logIn: 'Log In', alreadyHave: 'Already have an account?', signIn: 'Sign In',
    arabicTag: 'منصة إعادة التمويل المتوافقة مع الشريعة الإسلامية · الإمارات',
    slide1h: 'Ready to refinance smarter?', slide1s: 'One app. All your UAE debts. Best Sharia-compliant offers.',
    slide2h: 'See all your debts in one place', slide2s: 'Personal loans, cards, auto — unified, ranked, and ready to refinance.',
    slide3h: 'Convert to Sharia-compliant finance', slide3s: 'Switch from interest-based loans to certified Murābaḥa, Tawarruq & Ijāra.',
    slide4h: 'Know your real credit health', slide4s: 'Free CBUAE score + our proprietary OLFI Score — understand every factor.',
    dashboard: 'Dashboard', totalDebt: 'Total Debt', monthlyEMI: 'Monthly EMI', yourScore: 'Your Score',
    goodMorning: 'Good morning,', opportunities: 'Refinance Opportunity', savePer: 'Save AED', perMonth: '/mo',
    liabilities: 'Your Liabilities', viewAll: 'View All →', offers: 'Offers', score: 'Score', profile: 'Profile',
    home: 'Home', applyNow: 'Apply Now', bestMatch: '★ BEST MATCH', profitRate: 'profit rate',
    monthlySaving: 'Monthly Saving', newEMI: 'New EMI', scoreMatch: 'Score Match',
    filterAll: 'All', filterAPR: 'Lowest APR', filterEMI: 'Lowest EMI', filterFast: 'Fastest', filterTerm: 'Shortest Term',
    shariaOnly: '✦ Sharia-Compliant Offers Only',
  },
  ar: {
    getStarted: 'ابدأ الآن', logIn: 'تسجيل الدخول', alreadyHave: 'لديك حساب بالفعل؟', signIn: 'تسجيل الدخول',
    arabicTag: 'منصة إعادة التمويل المتوافقة مع الشريعة الإسلامية · الإمارات',
    slide1h: 'هل أنت مستعد لإعادة التمويل بذكاء؟', slide1s: 'تطبيق واحد. جميع ديونك في الإمارات. أفضل العروض الإسلامية.',
    slide2h: 'اطّلع على جميع ديونك في مكان واحد', slide2s: 'القروض الشخصية، البطاقات، السيارات — موحّدة ومصنّفة.',
    slide3h: 'تحوّل إلى التمويل الإسلامي', slide3s: 'انتقل من القروض الربوية إلى المرابحة والتورق والإجارة.',
    slide4h: 'اعرف صحّتك الائتمانية الحقيقية', slide4s: 'درجة المصرف المركزي مجانًا + درجة أولفي الخاصة.',
    dashboard: 'الرئيسية', totalDebt: 'إجمالي الديون', monthlyEMI: 'القسط الشهري', yourScore: 'درجتك',
    goodMorning: 'صباح الخير،', opportunities: 'فرصة إعادة التمويل', savePer: 'وفّر درهم', perMonth: '/شهر',
    liabilities: 'التزاماتك', viewAll: 'عرض الكل →', offers: 'العروض', score: 'الدرجة', profile: 'الملف',
    home: 'الرئيسية', applyNow: 'تقدّم الآن', bestMatch: '★ الأفضل', profitRate: 'معدل الربح',
    monthlySaving: 'التوفير الشهري', newEMI: 'القسط الجديد', scoreMatch: 'تطابق الدرجة',
    filterAll: 'الكل', filterAPR: 'أقل نسبة', filterEMI: 'أقل قسط', filterFast: 'الأسرع', filterTerm: 'أقصر مدة',
    shariaOnly: '✦ عروض متوافقة مع الشريعة فقط',
  },
  ur: {
    getStarted: 'شروع کریں', logIn: 'لاگ ان', alreadyHave: 'پہلے سے اکاؤنٹ ہے؟', signIn: 'سائن ان کریں',
    arabicTag: 'شریعت کے مطابق ری فائنانس پلیٹ فارم · یو اے ای',
    slide1h: 'ہوشیاری سے ری فائنانس کریں؟', slide1s: 'ایک ایپ۔ تمام UAE قرضے۔ بہترین اسلامی آفرز۔',
    slide2h: 'تمام قرضے ایک جگہ دیکھیں', slide2s: 'پرسنل لون، کارڈ، کار — یکجا، مرتب، ری فائنانس کے لیے تیار۔',
    slide3h: 'اسلامی مالیات میں تبدیل ہوں', slide3s: 'سودی قرضوں سے مرابحہ، تورق اور اجارہ میں منتقل ہوں۔',
    slide4h: 'اپنی کریڈٹ صحت جانیں', slide4s: 'مفت CBUAE اسکور + ہمارا OLFI اسکور۔',
    dashboard: 'ڈیش بورڈ', totalDebt: 'کل قرضہ', monthlyEMI: 'ماہانہ EMI', yourScore: 'آپ کا اسکور',
    goodMorning: 'صبح بخیر،', opportunities: 'ری فائنانس موقع', savePer: 'بچائیں AED', perMonth: '/ماہ',
    liabilities: 'آپ کے قرضے', viewAll: 'سب دیکھیں →', offers: 'آفرز', score: 'اسکور', profile: 'پروفائل',
    home: 'ہوم', applyNow: 'ابھی اپلائی کریں', bestMatch: '★ بہترین', profitRate: 'منافع کی شرح',
    monthlySaving: 'ماہانہ بچت', newEMI: 'نئی EMI', scoreMatch: 'اسکور میچ',
    filterAll: 'سب', filterAPR: 'کم APR', filterEMI: 'کم EMI', filterFast: 'تیز ترین', filterTerm: 'مختصر مدت',
    shariaOnly: '✦ صرف شریعت کے مطابق آفرز',
  },
  hi: {
    getStarted: 'शुरू करें', logIn: 'लॉग इन', alreadyHave: 'पहले से खाता है?', signIn: 'साइन इन करें',
    arabicTag: 'शरिया-अनुपालक रिफाइनेंस प्लेटफॉर्म · UAE',
    slide1h: 'स्मार्ट रिफाइनेंस के लिए तैयार?', slide1s: 'एक ऐप। सभी UAE लोन। सर्वश्रेष्ठ इस्लामिक ऑफर।',
    slide2h: 'सभी कर्ज एक जगह देखें', slide2s: 'पर्सनल लोन, कार्ड, ऑटो — एकीकृत और रिफाइनेंस के लिए तैयार।',
    slide3h: 'शरिया-अनुपालक वित्त में बदलें', slide3s: 'ब्याज-आधारित लोन से मुरबाहा, तवारुक और इजारा में स्विच करें।',
    slide4h: 'अपना असली क्रेडिट स्कोर जानें', slide4s: 'मुफ़्त CBUAE स्कोर + हमारा OLFI स्कोर।',
    dashboard: 'डैशबोर्ड', totalDebt: 'कुल कर्ज', monthlyEMI: 'मासिक EMI', yourScore: 'आपका स्कोर',
    goodMorning: 'सुप्रभात,', opportunities: 'रिफाइनेंस अवसर', savePer: 'बचाएं AED', perMonth: '/माह',
    liabilities: 'आपके लोन', viewAll: 'सब देखें →', offers: 'ऑफर', score: 'स्कोर', profile: 'प्रोफाइल',
    home: 'होम', applyNow: 'अभी आवेदन करें', bestMatch: '★ सर्वश्रेष्ठ', profitRate: 'लाभ दर',
    monthlySaving: 'मासिक बचत', newEMI: 'नई EMI', scoreMatch: 'स्कोर मिलान',
    filterAll: 'सभी', filterAPR: 'कम APR', filterEMI: 'कम EMI', filterFast: 'सबसे तेज़', filterTerm: 'कम अवधि',
    shariaOnly: '✦ केवल शरिया-अनुपालक ऑफर',
  },
} as const;
